# Numpy

In [2]:
import numpy as np
import sys

In [4]:
a = np.array([1,2,3], dtype='int8')
b = np.array([[1.0, 2.3, 1.5], [2, 3.1, 6.9]])
print(a)
b

[1 2 3]


array([[1. , 2.3, 1.5],
       [2. , 3.1, 6.9]])

In [5]:
a.ndim # Get dimension

1

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int8')

In [8]:
a.itemsize # byted occupied by each item

1

In [9]:
a.nbytes

3

## Accessing an array

In [11]:
a = np.array ([[1,2,3,4, 5, 6,7], [8,9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
a[1, -2]

13

In [14]:
print(a[1, :])
a[:,2]

[ 8  9 10 11 12 13 14]


array([ 3, 10])

In [18]:
a[1,5] = 21
a[:,2] = [34,35]
a

array([[ 1,  2, 34,  4,  5,  6,  7],
       [ 8,  9, 35, 11, 12, 21, 14]])

## Initializing arrays

In [22]:
print(np.zeros(7))
print(np.zeros((2,2,3)))
np.ones(6)

[0. 0. 0. 0. 0. 0. 0.]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


array([1., 1., 1., 1., 1., 1.])

In [21]:
np.full((1,2),54)

array([[54, 54]])

In [23]:
np.random.rand(3,4)

array([[0.73338228, 0.41918643, 0.75660538, 0.73291577],
       [0.47660862, 0.5781473 , 0.79521703, 0.96382834],
       [0.18281101, 0.85976971, 0.05859015, 0.26584081]])

In [24]:
np.random.randint(7, size=(3,2))

array([[6, 3],
       [3, 3],
       [1, 2]])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
x = np.ones((5,5))
x[1:-1,1:-1] = np.zeros((3,3))
x[2,2] = 9
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
# deep copy
b = a.copy()

## Mathematics

In [40]:
a = np.array([1,2,3])
a=a+2      # Similarly - / *
a 

array([3, 4, 5])

In [41]:
b = [3,7,10]
a+b

array([ 6, 11, 15])

In [43]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427])

## Linear Algebra

In [45]:
a = np.ones((3,2))
b = np.full((2,3), 9)
np.matmul(a,b) # Matrix Multiplication

array([[18., 18., 18.],
       [18., 18., 18.],
       [18., 18., 18.]])

In [49]:
a = np.identity(3)
np.linalg.det(a)

1.0

## Statistics

In [56]:
a = np.array([[1,2,3],[4,1,6]])
np.sum(a, axis=0)

array([5, 3, 9])

In [55]:
print(np.min(a))
print(np.min(a, axis=1))
print(np.min(a, axis=0))

1
[1 1]
[1 1 3]


In [64]:
a = np.random.randint(1,100, size=(5,5))
a

array([[62, 64, 97, 79, 53],
       [93, 63, 75, 55, 33],
       [66, 87, 65, 69, 43],
       [59, 38, 32, 66, 51],
       [30, 22, 29, 83,  7]])

In [59]:
a[a>5] # print all elements > 5

array([14, 49, 52,  6, 52, 46, 16, 62, 80, 96, 34, 13, 10,  8, 37, 67, 43,
       52, 83, 91, 67, 62, 11, 33])

In [67]:
np.any(a>50, axis=0) # if each column has any element > 50
np.all(a>20, axis=0) # if each column has all elements > 20

array([ True,  True,  True,  True, False])

The condition a>5 can be replaced by any other condition/compound condition